version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 8000
    ports:
      - 8002:8000
    depends_on:
      - db

  db:
    image: mysql:latest
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: 'Panorama'
      MYSQL_USER: 'web'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: 'rootegor'
    restart: always







